### ISSUE TITLE
Error with importing the plotting module

### ISSUE THREAD

**Issue by athantas95** [netneurolab/netneurotools#124]
I get an error with importing the plotting module. That is in freesurfer.py, line 13:
`ImportError: cannot import name '_stats' from 'scipy.ndimage.measurements'`

version of scipy == 1.10.0

**Comment by liuzhenqi77** [comment]
Hi, thanks for reporting the issue.

This should have been fixed by [this commit](https://github.com/netneurolab/netneurotools/commit/86417f93aea01667bba3324713a818c08fe64eeb). You can re-install netneurotools from GitHub main branch to make use of the fix. We are working on making the next release soon. Please feel free to let us know if you have more questions.

Best,
Zhen-Qi
