### ISSUE TITLE
Can't find fetch_vazquez_rodriguez2019 attribute 

### ISSUE THREAD

**Issue by giuliabaracc** [netneurolab/netneurotools#69]
Hi,

 I am new to Pyhton and I am trying to run your "Spatial permutations for significance testing" example in Jupyter Notebook. After installing netneurotools in Python 3, I get the following error:
<img width="1085" alt="Screen Shot 2020-01-23 at 12 27 56 PM" src="https://user-images.githubusercontent.com/31424991/73008095-d17d3f80-3ddb-11ea-9ef0-6953625a22ce.png">

I looked at fetchers.py and found the definition of the function but somehow it doesn't seem to be able to find the attribute. Am I missing something?

Best,
Giulia

**Comment by rmarkello** [comment]
Hi @giuliabaracc!

Welcome to `netneurotools` and thanks for the issue! You ran the code exactly correctly—I just made a slight error when adding that function to the toolbox so you should get the right results if you do:

```python
from netneurotools.datasets.fetchers import  fetch_vazquez_rodriguez2019
```

And then call the function (without the `nndata` prefix) in the future like:

```python
data = fetch_vazquez_rodriguez2019(verbose=0)
```

I'll fix the error you ran into as soon as I'm back at a computer so that the code you ran will work in the next release.

One more note: the example you're using is a work-in-progress (I actually thought I'd temporarily removed it from the documentation but apparently not!) and should come with a huge "your mileage may vary" warning! I'm actually working on a project to investigate how _much_ your mileage may vary. Nonetheless, let me know if you have questions as you go through it—just know I might not necessarily have good answers.

Hope that helps!

**Comment by giuliabaracc** [comment]
ahahah! Yes it makes sense. Thank you, will keep you posted.

**Comment by rmarkello** [comment]
Just for the sake of documenting our off-line discussion, the reason for this error was that you had installed `netneurotools` via pip and the necessary functionality (i.e., `fetch_vazquez_rodriguez2019`) has not yet made it into a PyPi release. We were able to resolve the error by installing from GitHub (`pip install git+https://github.com/netneurolab/netneurotools.git`). Once a new release is made and uploaded to PyPi then this shouldn't be a problem!

There were some other minor issues with the example code, but that is largely because it hasn't been updated in-sync with `netneurotools` as a whole. I will be removing the relevant example from the generated documentation in a future commit until it's a bit more well-developed.

Let me know if you run into any more problems, @giuliabaracc ! Otherwise I'm going to close this issue for now.
