### ISSUE TITLE
Conversion to float in freesurfer.parcels_to_vertices

### ISSUE THREAD

**Issue by VinceBaz** [netneurolab/netneurotools#84]
Here's a very minor issue that annoyed me this morning : 
In freesurfer.parcels_to_vertices, we might want to handle cases where the parcellated data to be projected on the vertices are int values since np.nan cannot be inserted into numpy arrays of int. We could for example convert ints to floats. Without proper handling of this case, the user might be confused as to what goes wrong when the "cannot convert float NaN to integer" ValueError is raised.

**Comment by rmarkello** [comment]
Seems reasonable! Should be as straightforward as modifying:

https://github.com/netneurolab/netneurotools/blob/4ff61eb5452f90a5366a289c91c9ad2ed0fd2940/netneurotools/freesurfer.py#L279

to:

```python
data = np.vstack(data).astype('float')
```

Feel free to open a PR with the changes 🙌 

(Alternatively, instead of casting ourselves we could just raise a more helpful error, i.e., if an int array is detected let the user know that they need to cast to float to use the function. Your choice!)
